# Generated by Django 4.1.1 on 2022-09-26 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spatialdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN', models.CharField(blank=True, max_length=50)),
                ('ISO_A3', models.CharField(blank=True, max_length=3)),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
