# Generated by Django 4.0.7 on 2022-09-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('worldviewer', '0003_remove_spatialdata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdata',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
