# Generated by Django 4.0.7 on 2022-09-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldviewer', '0005_remove_spatialdata_task_alter_spatialdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spatialdata',
            table=None,
        ),
    ]
